apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw0
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hw0
        image: good_nginx0:local
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hw0-service
spec:
  type: LoadBalancer
  selector: 
    app: nginx 
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80