apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: hw0
        image: good_mongo:local
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: hw2-service
spec:
  type: LoadBalancer
  selector: 
    app: mongo 
  ports: 
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30356
